#!/bin/sh
#$ -j y
#$ -cwd
#$ -l h_rt=01:00:00
#$ -A fim
#$ -N run_gsi_hybrid
#$ -o run_gsi_hybrid.out
#$ -e run_gsi_hybrid.err
#$ -pe ncomp 128
#$ -S /bin/sh

VERBOSE=${VERBOSE:-"NO"}
if [[ "$VERBOSE" = "YES" ]]; then
   set -x
fi
 

# Set experiment name and analysis date
adate=$analdate
nens=$nanals

HXONLY=${HXONLY:-"NO"}

if [[ "$HXONLY" = "YES" ]]; then
    SKIP_ANGUPDATE=${SKIP_ANGUPDATE:-"YES"}
    lread_obs_save=${lread_obs_save:-.false.}
    lread_obs_skip=${lread_obs_skip:-.true.}
    CLEAN=${CLEAN:-"YES"}
else
    SKIP_ANGUPDATE=${SKIP_ANGUPDATE:-"NO"}
    lread_obs_save=${lread_obs_save:-.true.}
    lread_obs_skip=${lread_obs_skip:-.false.}
    CLEAN=${CLEAN:-"NO"}
fi
NPROCS=${nprocs:-$NSLOTS}



# Set path/file for gsi executable
basedir=/lfs1/projects/fim/whitaker/ncepsvn
gsipath=${gsipath:-$basedir/gsi}
gsiexec=$gsipath/src/global_gsi
angupdatexec=${basedir}/global_angupdate.fd/global_angupdate
charnanal=${charnanal:-'ensmean'}
# name just for diag files.
charnanal2=${charnanal2:-$charnanal}


# Set the JCAP resolution which you want.
# All resolutions use LEVS=64
export JCAP=${JCAP:-382}
export LEVS=${LEVS:-64}
export JCAP_B=$JCAP


# Set runtime and save directories
tmpdir=${tmpdir:-datapath2/gsitmp$$}
savdir=${savdir:-$datapath2}

SFCANL=${SFCANL:-$savdir/sfcanl.${adate}}
SIGANL=${SIGANL:-$savdir/siganl.${adate}}

# Specify GSI fixed field and data directories.
fixgsi=$gsipath/fix
fixcrtm=$fixgsi/crtm_gfsgsi
CYCLESH=${CYCLESH:-$gsipath/scripts/global_cyclep.sh}


# Set variables used in script
#   CLEAN up $tmpdir when finished (YES=remove, NO=leave alone)
#   ndate is a date manipulation utility
#   ndate is a date manipulation utility
#   ncp is cp replacement, currently keep as /bin/cp

ndate=/whome/whitaker/bin/ndate
ncp="/bin/cp -f"
nmv="/bin/mv -f"
nln="/bin/ln -fs"


# Given the requested resolution, set dependent resolution parameters
if [[ "$JCAP" = "382" ]]; then
   export LONA=784 
   export LATA=368
   export DELTIM=180
elif [[ "$JCAP" = "62" ]]; then
   export LONA:LONA=192
   export LATA=94
   export DELTIM=1200
elif [[ "$JCAP" = "126" ]]; then
   export LONA=384
   export LATA=190
   export DELTIM=600 
elif [[ "$JCAP" = "190" ]]; then
   export LONA=576
   export LATA=288
   export DELTIM=400 
else
   echo "INVALID JCAP = $JCAP"
   exit
fi
export NLAT=$((${LATA}+2))


# Given the analysis date, compute the date from which the
# first guess comes.  Extract cycle and set prefix and suffix
# for guess and observation data files
gdate=`$ndate -06 $adate`
hha=`echo $adate | cut -c9-10`
hhg=`echo $gdate | cut -c9-10`
RUN=${RUN:-gfs}
prefix_obs=${RUN}.t${hha}z
prefix_tbc=${RUN}.t${hhg}z
suffix=tm00.bufr_d

adate0=`echo $adate | cut -c1-8`
iy=`echo $adate | cut -c1-4`
im=`echo $adate | cut -c5-6`
id=`echo $adate | cut -c7-8`
ih=`echo $adate | cut -c9-10`
gdate0=`echo $gdate | cut -c1-8`
datobs=$obs_datapath/bufr_$adate
datges=$datapath2
datgesm1=$datapathm1



# go to $tmpdir
cd $tmpdir


# Make gsi namelist
SETUP="lread_obs_save=$lread_obs_save,lread_obs_skip=$lread_obs_skip"
if [[ "$HXONLY" = "YES" ]]; then
   SETUP="$SETUP,lwrtinc=.true.,l4dvar=.true.,lobserver=.true."
fi
GRIDOPTS=""
BKGVERR=""
ANBKGERR=""
JCOPTS=""
STRONGOPTS=""
OBSQC=""
OBSINPUT=""
SUPERRAD=""
SINGLEOB=""
LAGDATA=""
#      l_hyb_ens:  logical variable, if .true., then turn on hybrid ensemble option, default = .false. 
#      n_ens:      ensemble size, default = 0
#      beta1_inv:  value between 0 and 1, relative weight given to static background B, default = 1.0
#      s_ens_h:    horizontal localization correlation length (units of km), default = 2828.0
#      s_ens_v:    vertical localization correlation length (grid units), default = 30.0
#      generate_ens:  if .true., generate ensemble perturbations internally as random samples of background B.
#                       (used primarily for testing/debugging)
#                     if .false., read external ensemble perturbations (not active yet)
#      aniso_a_en: if .true., then allow anisotropic localization correlation (not active yet)
#      uv_hyb_ens: if .true., then ensemble perturbation wind stored as u,v
#                  if .false., ensemble perturbation wind stored as psi,chi.
#                   (this is useful for regional application, where there is ambiguity in how to
#                      define psi,chi from u,v)
if [[ $beta1_inv < 0.999 ]]; then
HYBRIDENSDATA="l_hyb_ens=.true.,n_ens=$nens,beta1_inv=$beta1_inv,s_ens_h=$s_ens_h,s_ens_v=$s_ens_v,generate_ens=.false.,uv_hyb_ens=.true.,jcap_ens=$JCAP,nlat_ens=$LATA,nlon_ens=$LONA,ANISO_A_EN=.false.,jcap_ens_test=$JCAP"
#HYBRIDENSDATA="l_hyb_ens=.true.,n_ens=$nens,beta1_inv=$beta1_inv,s_ens_h=$s_ens_h,s_ens_v=$s_ens_v,generate_ens=.false.,uv_hyb_ens=.true.,jcap_en=$JCAP"
else
HYBRIDENSDATA=""
fi

GRIDOPTS="JCAP_B=$JCAP_B"

##!   l4dvar=.false.,nhr_assimilation=6,nhr_obsbin=6,
##!   lsqrtb=.true.,lcongrad=.false.,ltlint=.true.,
##!   idmodel=.true.,lwrtinc=.false.,

cat << EOF > gsiparm.anl
 &SETUP
   miter=2,niter(1)=100,niter(2)=150,
   niter_no_qc(1)=50,niter_no_qc(2)=0,
   write_diag(1)=.true.,write_diag(2)=.false.,write_diag(3)=.true.,
   gencode=$IGEN,qoption=2,
   factqmin=0.000,factqmax=0.000,deltim=$DELTIM,
   ndat=63,npred=5,iguess=-1,
   oneobtest=.false.,retrieval=.false.,l_foto=.false.,
   use_pbl=.false.,print_diag_pcg=.true.,
   $SETUP
 /
 &GRIDOPTS
   JCAP=$JCAP,NLAT=$NLAT,NLON=$LONA,nsig=$LEVS,hybrid=.true.,
   regional=.false.,nlayers(63)=3,nlayers(64)=6,
   $GRIDOPTS
 /
 &BKGERR
   as=0.6,0.6,0.75,0.75,0.75,0.75,1.0,1.0
   vs=0.7,
   hzscl=1.7,0.8,0.5,
   hswgt=0.45,0.3,0.25,
   bw=0.0,norsp=4,
   bkgv_flowdep=.true.,bkgv_rewgtfct=1.5,
   tsfc_sdv(1)=3.0,tsfc_sdv(2)=3.0,
   $BKGVERR
 /
 &ANBKGERR
   anisotropic=.false.,
   $ANBKGERR
 /
 &JCOPTS
   $JCOPTS
 /
 &STRONGOPTS
   jcstrong=.true.,nstrong=1,nvmodes_keep=8,period_max=6.,period_width=1.5,
   jcstrong_option=2,baldiag_full=.true.,baldiag_inc=.true.,
   $STRONGOPTS
 /
 &OBSQC
   dfact=0.75,dfact1=3.0,noiqc=.true.,oberrflg=.false.,c_varqc=0.02,
   use_poq7=.true.,
   $OBSQC
 /
 &OBS_INPUT
   dmesh(1)=180.0,dmesh(2)=145.0,dmesh(3)=240.0,dmesh(4)=160.0,dmesh(5)=180.0,dmesh(6)=150.0,time_window_max=3.0,
   dfile(01)='prepbufr',  dtype(01)='ps',        dplat(01)=' ',         dsis(01)='ps',                  dval(01)=1.0,  dthin(01)=0,
   dfile(02)='prepbufr'   dtype(02)='t',         dplat(02)=' ',         dsis(02)='t',                   dval(02)=1.0,  dthin(02)=0,
   dfile(03)='prepbufr',  dtype(03)='q',         dplat(03)=' ',         dsis(03)='q',                   dval(03)=1.0,  dthin(03)=0,
   dfile(04)='prepbufr',  dtype(04)='uv',        dplat(04)=' ',         dsis(04)='uv',                  dval(04)=1.0,  dthin(04)=0,
   dfile(05)='prepbufr',  dtype(05)='spd',       dplat(05)=' ',         dsis(05)='spd',                 dval(05)=1.0,  dthin(05)=0,
   dfile(06)='radarbufr', dtype(06)='rw',        dplat(06)=' ',         dsis(06)='rw',                  dval(06)=1.0,  dthin(06)=0,
   dfile(07)='prepbufr',  dtype(07)='dw',        dplat(07)=' ',         dsis(07)='dw',                  dval(07)=1.0,  dthin(07)=0,
   dfile(08)='prepbufr',  dtype(08)='sst',       dplat(08)=' ',         dsis(08)='sst',                 dval(08)=1.0,  dthin(08)=0,
   dfile(09)='prepbufr',  dtype(09)='pw',        dplat(09)=' ',         dsis(09)='pw',                  dval(09)=1.0,  dthin(09)=0,
   dfile(10)='gpsrobufr', dtype(10)='gps_ref',   dplat(10)=' ',         dsis(10)='gps_ref',             dval(10)=1.0,  dthin(10)=0,
   dfile(11)='ssmirrbufr',dtype(11)='pcp_ssmi',  dplat(11)='dmsp',      dsis(11)='pcp_ssmi',            dval(11)=1.0,  dthin(11)=-1,
   dfile(12)='tmirrbufr', dtype(12)='pcp_tmi',   dplat(12)='trmm',      dsis(12)='pcp_tmi',             dval(12)=1.0,  dthin(12)=-1,
   dfile(13)='sbuvbufr',  dtype(13)='sbuv2',     dplat(13)='n16',       dsis(13)='sbuv8_n16',           dval(13)=1.0,  dthin(13)=0,
   dfile(14)='sbuvbufr',  dtype(14)='sbuv2',     dplat(14)='n17',       dsis(14)='sbuv8_n17',           dval(14)=1.0,  dthin(14)=0,
   dfile(15)='sbuvbufr',  dtype(15)='sbuv2',     dplat(15)='n18',       dsis(15)='sbuv8_n18',           dval(15)=1.0,  dthin(15)=0,
   dfile(16)='omi',       dtype(16)='omi',       dplat(16)='aura',      dsis(16)='omi_aura',            dval(16)=1.0,  dthin(16)=6,
   dfile(17)='hirs2bufr', dtype(17)='hirs2',     dplat(17)='n14',       dsis(17)='hirs2_n14',           dval(17)=6.0,  dthin(17)=1,
   dfile(18)='hirs3bufr', dtype(18)='hirs3',     dplat(18)='n16',       dsis(18)='hirs3_n16',           dval(18)=0.0,  dthin(18)=1,
   dfile(19)='hirs3bufr', dtype(19)='hirs3',     dplat(19)='n17',       dsis(19)='hirs3_n17',           dval(19)=6.0,  dthin(19)=1,
   dfile(20)='hirs4bufr', dtype(20)='hirs4',     dplat(20)='n18',       dsis(20)='hirs4_n18',           dval(20)=0.0,  dthin(20)=1,
   dfile(21)='hirs4bufr', dtype(21)='hirs4',     dplat(21)='metop-a',   dsis(21)='hirs4_metop-a',       dval(21)=6.0,  dthin(21)=1,
   dfile(22)='gsndrbufr', dtype(22)='sndr',      dplat(22)='g11',       dsis(22)='sndr_g11',            dval(22)=0.0,  dthin(22)=1,
   dfile(23)='gsndrbufr', dtype(23)='sndr',      dplat(23)='g12',       dsis(23)='sndr_g12',            dval(23)=0.0,  dthin(23)=1,
   dfile(24)='gimgrbufr', dtype(24)='goes_img',  dplat(24)='g11',       dsis(24)='imgr_g11',            dval(24)=0.0,  dthin(24)=1,
   dfile(25)='gimgrbufr', dtype(25)='goes_img',  dplat(25)='g12',       dsis(25)='imgr_g12',            dval(25)=0.0,  dthin(25)=1,
   dfile(26)='airsbufr',  dtype(26)='airs',      dplat(26)='aqua',      dsis(26)='airs281SUBSET_aqua',  dval(26)=20.0, dthin(26)=1,
   dfile(27)='msubufr',   dtype(27)='msu',       dplat(27)='n14',       dsis(27)='msu_n14',             dval(27)=2.0,  dthin(27)=2,
   dfile(28)='amsuabufr', dtype(28)='amsua',     dplat(28)='n15',       dsis(28)='amsua_n15',           dval(28)=10.0, dthin(28)=2,
   dfile(29)='amsuabufr', dtype(29)='amsua',     dplat(29)='n16',       dsis(29)='amsua_n16',           dval(29)=0.0,  dthin(29)=2,
   dfile(30)='amsuabufr', dtype(30)='amsua',     dplat(30)='n17',       dsis(30)='amsua_n17',           dval(30)=0.0,  dthin(30)=2,
   dfile(31)='amsuabufr', dtype(31)='amsua',     dplat(31)='n18',       dsis(31)='amsua_n18',           dval(31)=10.0, dthin(31)=2,
   dfile(32)='amsuabufr', dtype(32)='amsua',     dplat(32)='metop-a',   dsis(32)='amsua_metop-a',       dval(32)=10.0, dthin(32)=2,
   dfile(33)='airsbufr',  dtype(33)='amsua',     dplat(33)='aqua',      dsis(33)='amsua_aqua',          dval(33)=5.0,  dthin(33)=2,
   dfile(34)='amsubbufr', dtype(34)='amsub',     dplat(34)='n15',       dsis(34)='amsub_n15',           dval(34)=3.0,  dthin(34)=3,
   dfile(35)='amsubbufr', dtype(35)='amsub',     dplat(35)='n16',       dsis(35)='amsub_n16',           dval(35)=3.0,  dthin(35)=3,
   dfile(36)='amsubbufr', dtype(36)='amsub',     dplat(36)='n17',       dsis(36)='amsub_n17',           dval(36)=3.0,  dthin(36)=3,
   dfile(37)='mhsbufr',   dtype(37)='mhs',       dplat(37)='n18',       dsis(37)='mhs_n18',             dval(37)=3.0,  dthin(37)=3,
   dfile(38)='mhsbufr',   dtype(38)='mhs',       dplat(38)='metop-a',   dsis(38)='mhs_metop-a',         dval(38)=3.0,  dthin(38)=3,
   dfile(39)='ssmitbufr', dtype(39)='ssmi',      dplat(39)='f13',       dsis(39)='ssmi_f13',            dval(39)=0.0,  dthin(39)=4,
   dfile(40)='ssmitbufr', dtype(40)='ssmi',      dplat(40)='f14',       dsis(40)='ssmi_f14',            dval(40)=0.0,  dthin(40)=4,
   dfile(41)='ssmitbufr', dtype(41)='ssmi',      dplat(41)='f15',       dsis(41)='ssmi_f15',            dval(41)=0.0,  dthin(41)=4,
   dfile(42)='amsrebufr', dtype(42)='amsre_low', dplat(42)='aqua',      dsis(42)='amsre_aqua',          dval(42)=0.0,  dthin(42)=4,
   dfile(43)='amsrebufr', dtype(43)='amsre_mid', dplat(43)='aqua',      dsis(43)='amsre_aqua',          dval(43)=0.0,  dthin(43)=4,
   dfile(44)='amsrebufr', dtype(44)='amsre_hig', dplat(44)='aqua',      dsis(44)='amsre_aqua',          dval(44)=0.0,  dthin(44)=4,
   dfile(45)='ssmisbufr', dtype(45)='ssmis_las', dplat(45)='f16',       dsis(45)='ssmis_f16',           dval(45)=0.0,  dthin(45)=4,
   dfile(46)='ssmisbufr', dtype(46)='ssmis_uas', dplat(46)='f16',       dsis(46)='ssmis_f16',           dval(46)=0.0,  dthin(46)=4,
   dfile(47)='ssmisbufr', dtype(47)='ssmis_img', dplat(47)='f16',       dsis(47)='ssmis_f16',           dval(47)=0.0,  dthin(47)=4,
   dfile(48)='ssmisbufr', dtype(48)='ssmis_env', dplat(48)='f16',       dsis(48)='ssmis_f16',           dval(48)=0.0,  dthin(48)=4,
   dfile(49)='gsnd1bufr', dtype(49)='sndrd1',    dplat(49)='g12',       dsis(49)='sndrD1_g12',          dval(49)=1.5,  dthin(49)=5,
   dfile(50)='gsnd1bufr', dtype(50)='sndrd2',    dplat(50)='g12',       dsis(50)='sndrD2_g12',          dval(50)=1.5,  dthin(50)=5,
   dfile(51)='gsnd1bufr', dtype(51)='sndrd3',    dplat(51)='g12',       dsis(51)='sndrD3_g12',          dval(51)=1.5,  dthin(51)=5,
   dfile(52)='gsnd1bufr', dtype(52)='sndrd4',    dplat(52)='g12',       dsis(52)='sndrD4_g12',          dval(52)=1.5,  dthin(52)=5,
   dfile(53)='gsnd1bufr', dtype(53)='sndrd1',    dplat(53)='g11',       dsis(53)='sndrD1_g11',          dval(53)=1.5,  dthin(53)=5,
   dfile(54)='gsnd1bufr', dtype(54)='sndrd2',    dplat(54)='g11',       dsis(54)='sndrD2_g11',          dval(54)=1.5,  dthin(54)=5,
   dfile(55)='gsnd1bufr', dtype(55)='sndrd3',    dplat(55)='g11',       dsis(55)='sndrD3_g11',          dval(55)=1.5,  dthin(55)=5,
   dfile(56)='gsnd1bufr', dtype(56)='sndrd4',    dplat(56)='g11',       dsis(56)='sndrD4_g11',          dval(56)=1.5,  dthin(56)=5,
   dfile(57)='gsnd1bufr', dtype(57)='sndrd1',    dplat(57)='g13',       dsis(57)='sndrD1_g13',          dval(57)=1.5,  dthin(57)=5,
   dfile(58)='gsnd1bufr', dtype(58)='sndrd2',    dplat(58)='g13',       dsis(58)='sndrD2_g13',          dval(58)=1.5,  dthin(58)=5,
   dfile(59)='gsnd1bufr', dtype(59)='sndrd3',    dplat(59)='g13',       dsis(59)='sndrD3_g13',          dval(59)=1.5,  dthin(59)=5,
   dfile(60)='gsnd1bufr', dtype(60)='sndrd4',    dplat(60)='g13',       dsis(60)='sndrD4_g13',          dval(60)=1.5,  dthin(60)=5,
   dfile(61)='iasibufr',  dtype(61)='iasi',      dplat(61)='metop-a',   dsis(61)='iasi616_metop-a',     dval(61)=20.0, dthin(61)=1,
   dfile(62)='gomebufr',  dtype(62)='gome',      dplat(62)='metop-a',   dsis(62)='gome_metop-a',        dval(62)=1.0,  dthin(62)=6,
   dfile(63)='tcvitals',  dtype(63)='tcp',       dplat(63)=' ',         dsis(63)='tcp',                 dval(63)=1.0,  dthin(63)=0,
   $OBSINPUT
 /
  &SUPEROB_RADAR
   $SUPERRAD
 /
  &LAG_DATA
   $LAGDATA
 /
  &HYBRID_ENSEMBLE
   $HYBRIDENSDATA
 /
 &SINGLEOB_TEST
   maginnov=0.1,magoberr=0.1,oneob_type='t',
   oblat=45.,oblon=180.,obpres=1000.,obdattim=${adate},
   obhourset=0.,
   $SINGLEOB
 /

EOF

# Set fixed files
#   berror   = forecast model background error statistics
#   specoef  = CRTM spectral coefficients
#   trncoef  = CRTM transmittance coefficients
#   emiscoef = CRTM coefficients for IR sea surface emissivity model
#   aerocoef = CRTM coefficients for aerosol effects
#   cldcoef  = CRTM coefficients for cloud effects
#   satinfo  = text file with information about assimilation of brightness temperatures
#   satangl  = angle dependent bias correction file (fixed in time)
#   pcpinfo  = text file with information about assimilation of prepcipitation rates
#   ozinfo   = text file with information about assimilation of ozone data
#   errtable = text file with obs error for conventional data (optional)
#   convinfo = text file with information about assimilation of conventional data
#   bufrtable= text file ONLY needed for single obs test (oneobstest=.true.)
#   bftab_sst= bufr table for sst ONLY needed for sst retrieval (retrieval=.true.)

berror=$fixgsi/global_berror.l${LEVS}y${NLAT}.f77
emiscoef=$fixcrtm/EmisCoeff/Big_Endian/EmisCoeff.bin
aercoef=$fixcrtm/AerosolCoeff/Big_Endian/AerosolCoeff.bin
cldcoef=$fixcrtm/CloudCoeff/Big_Endian/CloudCoeff.bin
satinfo=$fixgsi/global_satinfo.txt
satangl=$fixgsi/global_satangbias.txt
pcpinfo=$fixgsi/global_pcpinfo.txt
ozinfo=$fixgsi/global_ozinfo.txt
convinfo=$fixgsi/global_convinfo.txt
errtable=$fixgsi/prepobs_errtable.global


# Only need this file for single obs test
bufrtable=$fixgsi/prepobs_prep.bufrtable

# Only need this file for sst retrieval
bftab_sst=$fixgsi/bufrtab.012

# Copy executable and fixed files to $tmpdir
$nln $gsiexec ./gsi.x

$nln $berror   ./berror_stats
$nln $emiscoef ./EmisCoeff.bin
$nln $aercoef  ./AerosolCoeff.bin
$nln $cldcoef  ./CloudCoeff.bin
$nln $satangl  ./satbias_angle
$nln $satinfo  ./satinfo
$nln $pcpinfo  ./pcpinfo
$nln $ozinfo   ./ozinfo
$nln $convinfo ./convinfo
$nln $errtable ./errtable

$nln $bufrtable ./prepobs_prep.bufrtable
$nln $bftab_sst ./bftab_sstphr


if [[ "$lread_obs_save" = ".true." ]]; then

satsens=`cd $fixcrtm/SpcCoeff/Big_Endian; ls -1 *.SpcCoeff.bin | cut -f1 -d"." `
for satsen in $satsens; do
    count=`grep -c $satsen $satinfo`
    if [[ $count -gt 0 ]]; then
    spccoeff=${satsen}.SpcCoeff.bin
    if  [[ ! -s $spccoeff ]]; then
       $nln $fixcrtm/SpcCoeff/Big_Endian/$spccoeff ./
       $nln $fixcrtm/TauCoeff/Big_Endian/${satsen}.TauCoeff.bin ./
    fi
    fi
done


# Copy observational data to $tmpdir
$nln $datobs/${prefix_obs}.prepbufr           ./prepbufr
$nln $datobs/${prefix_obs}.gpsro.${suffix}    ./gpsrobufr
$nln $datobs/${prefix_obs}.spssmi.${suffix}   ./ssmirrbufr
$nln $datobs/${prefix_obs}.sptrmm.${suffix}   ./tmirrbufr
$nln $datobs/${prefix_obs}.osbuv8.${suffix}   ./sbuvbufr
$nln $datobs/${prefix_obs}.goesfv.${suffix}   ./gsnd1bufr
$nln $datobs/${prefix_obs}.1bamua.${suffix}   ./amsuabufr
$nln $datobs/${prefix_obs}.1bamub.${suffix}   ./amsubbufr
$nln $datobs/${prefix_obs}.1bhrs2.${suffix}   ./hirs2bufr
$nln $datobs/${prefix_obs}.1bhrs3.${suffix}   ./hirs3bufr
$nln $datobs/${prefix_obs}.1bhrs4.${suffix}   ./hirs4bufr
$nln $datobs/${prefix_obs}.1bmhs.${suffix}    ./mhsbufr
$nln $datobs/${prefix_obs}.1bmsu.${suffix}    ./msubufr
$nln $datobs/${prefix_obs}.airsev.${suffix}   ./airsbufr
$nln $datobs/${prefix_obs}.mtiasi.${suffix}   ./iasibufr
$nln $datobs/${prefix_obs}.ssmit.${suffix}    ./ssmitbufr
$nln $datobs/${prefix_obs}.amsre.${suffix}    ./amsrebufr
$nln $datobs/${prefix_obs}.ssmis.${suffix}    ./ssmisbufr
$ncp /lfs1/projects/rtfim/tcvitals/tcvitals.${adate}.txt ./tcvitals

# Copy bias correction, atmospheric and surface files
GBIAS=${GBIAS:-$datgesm1/${prefix_tbc}.abias}
GSATANG=${GSATANG:-$datgesm1/${prefix_tbc}.satang}
$nln $GBIAS              ./satbias_in
$nln $GSATANG            ./satbias_angle

fi

SFCG03=${SFCG03:-$datges/bfg_${adate}_fhr03_${charnanal}}
$nln $SFCG03               ./sfcf03
SFCG04=${SFCG04:-$datges/bfg_${adate}_fhr04_${charnanal}}
$nln $SFCG04               ./sfcf04
SFCG05=${SFCG05:-$datges/bfg_${adate}_fhr05_${charnanal}}
$nln $SFCG05               ./sfcf05
SFCG06=${SFCG06:-$datges/bfg_${adate}_fhr06_${charnanal}}
$nln $SFCG06               ./sfcf06
SFCG07=${SFCG07:-$datges/bfg_${adate}_fhr07_${charnanal}}
$nln $SFCG07               ./sfcf07
SFCG08=${SFCG08:-$datges/bfg_${adate}_fhr08_${charnanal}}
$nln $SFCG08               ./sfcf08
SFCG09=${SFCG09:-$datges/bfg_${adate}_fhr09_${charnanal}}
$nln $SFCG09               ./sfcf09
SIGG03=${SIGG03:-$datges/sfg_${adate}_fhr03_${charnanal}}
$nln $SIGG03               ./sigf03
SIGG04=${SIGG04:-$datges/sfg_${adate}_fhr04_${charnanal}}
$nln $SIGG04               ./sigf04
SIGG05=${SIGG05:-$datges/sfg_${adate}_fhr05_${charnanal}}
$nln $SIGG05               ./sigf05
SIGG06=${SIGG06:-$datges/sfg_${adate}_fhr06_${charnanal}}
$nln $SIGG06               ./sigf06
SIGG07=${SIGG07:-$datges/sfg_${adate}_fhr07_${charnanal}}
$nln $SIGG07               ./sigf07
SIGG08=${SIGG08:-$datges/sfg_${adate}_fhr08_${charnanal}}
$nln $SIGG08               ./sigf08
SIGG09=${SIGG09:-$datges/sfg_${adate}_fhr09_${charnanal}}
$nln $SIGG09               ./sigf09

if [[ "$HXONLY" = "NO" ]]; then
if [[ $beta1_inv < 0.999 ]]; then
for ensfile in $datges/sfg_${adate}*mem*; do
 ensfilename=`basename $ensfile`
 memnum=`echo $ensfilename | cut -f4 -d"_" | cut -c4-6`
 $nln $ensfile ./sigf06_ens_mem${memnum}
done
fi
fi

# do surface analysis
export FNTSFA=$datobs/${prefix_obs}.sstgrb
export FNACNA=$datobs/${prefix_obs}.engicegrb
export FNSNOA=$datobs/${prefix_obs}.snogrb
$CYCLESH $SFCG06 sfcanl 
rc=$?
if [[ $rc -ne 0 ]];then
  echo "global_cycle failed with exit code $rc"
  exit 1
fi

# Run gsi.
if [ -s ./satbias_in ] && [ -s ./satbias_angle ] && [ -s ./sfcf03 ] && [ -s ./sfcf06 ] && [ -s ./sfcf09 ] && [ -s ./sigf03 ] && [ -s ./sigf06 ] && [ -s ./sigf09 ] && [ -s ./sfcanl ]; then
cat gsiparm.anl
$MPICH/bin/mpirun_rsh -hostfile $HOSTFILE -np $NPROCS $tmpdir/gsi.x 
rc=$?
if [[ $rc -ne 0 ]];then
  echo "GSI failed with exit code $rc"
  exit 1
fi
else
echo "some input files missing, exiting ..."
ls -l ./satbias_in
ls -l ./satbias_angle
ls -l ./sfcf03
ls -l ./sfcf06
ls -l ./sfcf09
ls -l ./sfcanl
ls -l ./sigf03
ls -l ./sigf06
ls -l ./sigf09
exit 1
fi

# Save output
mkdir -p $savdir

$nmv sfcanl      $SFCANL

if [[ "$HXONLY" = "NO" ]]; then
if [ -s ./siganl ] && [ -s ./satbias_out ]; then
$ncp siganl          $SIGANL
##$ncp satbias_out     $savdir/biascr.${adate}
$ncp satbias_out     $savdir/${RUN}.t${hha}z.abias
##$ncp sfcf06          $savdir/sfcf06.${gdate}
##$ncp sigf06          $savdir/sigf06.${gdate}
else
exit 1
fi
else
cat fort.2* > $savdir/gsistats.${adate}_${charnanal2}
fi

# Loop over first and last outer loops to generate innovation
# diagnostic files for indicated observation types (groups)
#
# NOTE:  Since we set miter=2 in GSI namelist SETUP, outer
#        loop 03 will contain innovations with respect to 
#        the analysis.  Creation of o-a innovation files
#        is triggered by write_diag(3)=.true.  The setting
#        write_diag(1)=.true. turns on creation of o-g
#        innovation files.
#


echo "Time before diagnostic loop is `date` "
#loops="01 03"
loops="01"
for loop in $loops; do

case $loop in
  01) string=ges;;
  03) string=anl;;
   *) string=$loop;;
esac

#  Collect diagnostic files for obs types (groups) below
   listall="hirs2_n14 msu_n14 sndr_g08 sndr_g11 sndr_g11 sndr_g12 sndr_g13 sndr_g08_prep sndr_g11_prep sndr_g12_prep sndr_g13_prep sndrd1_g11 sndrd2_g11 sndrd3_g11 sndrd4_g11 sndrd1_g12 sndrd2_g12 sndrd3_g12 sndrd4_g12 sndrd1_g13 sndrd2_g13 sndrd3_g13 sndrd4_g13 hirs3_n15 hirs3_n16 hirs3_n17 amsua_n15 amsua_n16 amsua_n17 amsub_n15 amsub_n16 amsub_n17 hsb_aqua airs_aqua amsua_aqua imgr_g08 imgr_g11 imgr_g12 pcp_ssmi_dmsp pcp_tmi_trmm conv sbuv2_n16 sbuv2_n17 sbuv2_n18 gome_metop-a omi_aura ssmi_f13 ssmi_f14 ssmi_f15 hirs4_n18 hirs4_metop-a amsua_n18 amsua_metop-a mhs_n18 mhs_metop-a amsre_low_aqua amsre_mid_aqua amsre_hig_aqua ssmis_las_f16 ssmis_uas_f16 ssmis_img_f16 ssmis_env_f16 iasi_metop-a"
   for type in $listall; do
      #count=`ls ${tmpdir}/dir.*/${type}_${loop}* | wc -l`
      count=`ls pe*${type}_${loop}* | wc -l`
      if [[ $count -gt 0 ]]; then
         #cat dir.*/${type}_${loop}* > diag_${type}_${string}.${adate}
         #cat pe*${type}_${loop}* > diag_${type}_${string}.${adate}
         cat pe*${type}_${loop}* > $savdir/diag_${type}_${string}.${adate}_${charnanal2}
         #compress diag_${type}_${string}.${adate}
         #$ncp diag_${type}_${string}.${adate}.Z $savdir/
         #$ncp diag_${type}_${string}.${adate} $savdir/
      fi
   done
done
echo "Time after diagnostic loop is `date` "

if [ ! -s $savdir/diag_conv_ges.${adate}_${charnanal2} ]; then
   exit 1
fi

if [[ "$SKIP_ANGUPDATE" = "YES" ]]; then
   exit 0
fi


$nln ./satbias_angle  ./satbias_ang.in
ls -l  ./satbias_ang.in
cat  ./satbias_ang.in
for type in $listrad; do
   if [[ -s $savdir/diag_${type}_ges.${adate}_${charnanal2} ]]; then
      $nln $savdir/diag_${type}_ges.${adate}_${charnanal2}  ./diag_${type}.$adate
   fi
done

cat  > global_angupdate.nml <<EOF
 &SETUP
  jpch=1459,nstep=90,nsize=20,wgtang=0.008333333,wgtlap=0.0,
  iuseqc=1,dtmax=1.0,
  iyy1=${iy},imm1=${im},idd1=${id},ihh1=${ih},
  iyy2=${iy},imm2=${im},idd2=${id},ihh2=${ih},
  dth=06,ndat=45,
  $SETUPANG
 /
 &OBS_INPUT
  dtype(01)='hirs2',     dplat(01)='n14',       dsis(01)='hirs2_n14',
  dtype(02)='hirs3',     dplat(02)='n16',       dsis(02)='hirs3_n16',
  dtype(03)='hirs3',     dplat(03)='n17',       dsis(03)='hirs3_n17',
  dtype(04)='hirs4',     dplat(04)='n18',       dsis(04)='hirs4_n18',
  dtype(05)='hirs4',     dplat(05)='metop-a',   dsis(05)='hirs4_metop-a',
  dtype(06)='sndr',      dplat(06)='g11',       dsis(06)='sndr_g11',
  dtype(07)='sndr',      dplat(07)='g12',       dsis(07)='sndr_g12',
  dtype(08)='goes_img',  dplat(08)='g11',       dsis(08)='imgr_g11',
  dtype(09)='goes_img',  dplat(09)='g12',       dsis(09)='imgr_g12',
  dtype(10)='airs',      dplat(10)='aqua',      dsis(10)='airs281SUBSET_aqua',
  dtype(11)='msu',       dplat(11)='n14',       dsis(11)='msu_n14',
  dtype(12)='amsua',     dplat(12)='n15',       dsis(12)='amsua_n15',
  dtype(13)='amsua',     dplat(13)='n16',       dsis(13)='amsua_n16',
  dtype(14)='amsua',     dplat(14)='n17',       dsis(14)='amsua_n17',
  dtype(15)='amsua',     dplat(15)='n18',       dsis(15)='amsua_n18',
  dtype(16)='amsua',     dplat(16)='metop-a',   dsis(16)='amsua_metop-a',
  dtype(17)='amsua',     dplat(17)='aqua',      dsis(17)='amsua_aqua',
  dtype(18)='amsub',     dplat(18)='n15',       dsis(18)='amsub_n15',
  dtype(19)='amsub',     dplat(19)='n16',       dsis(19)='amsub_n16',
  dtype(20)='amsub',     dplat(20)='n17',       dsis(20)='amsub_n17',
  dtype(21)='mhs',       dplat(21)='n18',       dsis(21)='mhs_n18',
  dtype(22)='mhs',       dplat(22)='metop-a',   dsis(22)='mhs_metop-a',
  dtype(23)='ssmi',      dplat(23)='f13',       dsis(23)='ssmi_f13',
  dtype(24)='ssmi',      dplat(24)='f14',       dsis(24)='ssmi_f14',
  dtype(25)='ssmi',      dplat(25)='f15',       dsis(25)='ssmi_f15',
  dtype(26)='amsre_low', dplat(26)='aqua',      dsis(26)='amsre_aqua',
  dtype(27)='amsre_mid', dplat(27)='aqua',      dsis(27)='amsre_aqua',
  dtype(28)='amsre_hig', dplat(28)='aqua',      dsis(28)='amsre_aqua',
  dtype(29)='ssmis_las', dplat(29)='f16',       dsis(29)='ssmis_f16',
  dtype(30)='ssmis_uas', dplat(30)='f16',       dsis(30)='ssmis_f16',
  dtype(31)='ssmis_img', dplat(31)='f16',       dsis(31)='ssmis_f16',
  dtype(32)='ssmis_env', dplat(32)='f16',       dsis(32)='ssmis_f16',
  dtype(33)='sndrd1',    dplat(33)='g12',       dsis(33)='sndrD1_g12',
  dtype(34)='sndrd2',    dplat(34)='g12',       dsis(34)='sndrD2_g12',
  dtype(35)='sndrd3',    dplat(35)='g12',       dsis(35)='sndrD3_g12',
  dtype(36)='sndrd4',    dplat(36)='g12',       dsis(36)='sndrD4_g12',
  dtype(37)='sndrd1',    dplat(37)='g11',       dsis(37)='sndrD1_g11',
  dtype(38)='sndrd2',    dplat(38)='g11',       dsis(38)='sndrD2_g11',
  dtype(39)='sndrd3',    dplat(39)='g11',       dsis(39)='sndrD3_g11',
  dtype(40)='sndrd4',    dplat(40)='g11',       dsis(40)='sndrD4_g11',
  dtype(41)='sndrd1',    dplat(41)='g13',       dsis(41)='sndrD1_g13',
  dtype(42)='sndrd2',    dplat(42)='g13',       dsis(42)='sndrD2_g13',
  dtype(43)='sndrd3',    dplat(43)='g13',       dsis(43)='sndrD3_g13',
  dtype(44)='sndrd4',    dplat(44)='g13',       dsis(44)='sndrD4_g13',
  dtype(45)='iasi',      dplat(45)='metop-a',   dsis(45)='iasi616_metop-a',
  $OBSINPUTANG
 /
EOF

cat global_angupdate.nml
mpirun -np $NSLOTS $angupdatexec
rc=$?
if [[ $rc -ne 0 ]];then
  echo "global_angupdate failed with exit code $rc"
  exit 1
fi
# Output file
##$ncp satbias_ang.out     $savdir/satang.${adate}
if [ -s satbias_ang.out ]; then
   $ncp satbias_ang.out     $savdir/${RUN}.t${hha}z.satang
else
   exit 1
fi


# If requested, clean up $tmpdir
if [[ "$CLEAN" = "YES" ]];then
   cd $tmpdir
   cd ../
   /bin/rm -rf $tmpdir
fi


# End of script
exit
