










C-----------------------------------------------------------------------
      FUNCTION NCPUS()
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM: NCPUS          SET NUMBER OF CPUS
C   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 94-08-19
C
C ABSTRACT: SET NUMBER OF CPUS 
C   DESIGNATING THE NUMBER OF PROCESSORS OVER WHICH TO PARALLELIZE.
C
C PROGRAM HISTORY LOG:
C   94-08-19  IREDELL
C   98-11-09  VUONG     ADD DOC BLOCK AND REMOVE CRAY REFERENCES
C 1998-12-18  IREDELL   IBM SMP VERSION
C 2009-12-27  DSTARK    updated the IBM specific version to function wo ESSL lib.
C
C USAGE:    NC=NCPUS()
C   OUTPUT ARGUMENTS:
C     NCPUS        INTEGER NUMBER OF CPUS
C
C SUBPROGRAMS CALLED:
C     NUM_PARTHDS  XLF INTRINSIC TO RETURN NUMBER OF THREADS
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C
C$$$
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

      INTEGER NTHREADS, TID, OMP_GET_NUM_THREADS,OMP_GET_THREAD_NUM

!     Obtain thread number

      NCPUS = 1
!#ifdef 1
!!$OMP PARALLEL PRIVATE(NCPUS, TID)
!      TID = OMP_GET_THREAD_NUM()
!      if (TID == 0) then
!         NCPUS = OMP_GET_NUM_THREADS()
!      endif
!!$OMP END PARALLEL
!#else
!      NCPUS = NUM_PARTHDS()
!#endif
      RETURN
      END
